import { createHash } from 'node:crypto';

const PROJECT_ID = process.env.FIREBASE_PROJECT_ID || process.env.GOOGLE_CLOUD_PROJECT || process.env.GCLOUD_PROJECT;
const DATABASE = '(default)';
const BASE = PROJECT_ID ? `https://firestore.googleapis.com/v1/projects/${encodeURIComponent(PROJECT_ID)}/databases/${encodeURIComponent(DATABASE)}/documents` : '';
type Doc = { name?: string; fields?: Record<string, Value> };
type Value = { stringValue?: string; integerValue?: string; doubleValue?: number; booleanValue?: boolean; nullValue?: string; timestampValue?: string; arrayValue?: { values?: Value[] }; mapValue?: { fields?: Record<string, Value> } };
const fromValue = (v?: Value): any => !v ? undefined : 'stringValue' in v ? v.stringValue : 'integerValue' in v ? Number(v.integerValue) : 'doubleValue' in v ? v.doubleValue : 'booleanValue' in v ? v.booleanValue : 'nullValue' in v ? null : 'timestampValue' in v ? v.timestampValue : 'arrayValue' in v ? (v.arrayValue?.values || []).map(fromValue) : 'mapValue' in v ? Object.fromEntries(Object.entries(v.mapValue?.fields || {}).map(([k,x]) => [k,fromValue(x)])) : undefined;
const fromDoc = (d?: Doc | null): Record<string,any> | null => !d ? null : Object.fromEntries(Object.entries(d.fields || {}).map(([k,v]) => [k,fromValue(v)]));
const toValue = (v: any): Value => v == null ? { nullValue:'NULL_VALUE' } : typeof v === 'string' ? {stringValue:v} : typeof v === 'boolean' ? {booleanValue:v} : typeof v === 'number' ? (Number.isInteger(v) ? {integerValue:String(v)} : {doubleValue:v}) : Array.isArray(v) ? {arrayValue:{values:v.map(toValue)}} : {mapValue:{fields:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,toValue(x)]))}};
const toDoc = (name:string,data:Record<string,unknown>):Doc => ({name,fields:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,toValue(v)]))});
const nameOf = (collection:string,id:string) => { if(!PROJECT_ID) throw new Error('FIREBASE_PROJECT_ID is required for trusted Firestore operations'); return `${BASE}/${collection}/${encodeURIComponent(id)}`; };
async function token(){ if(process.env.GOOGLE_OAUTH_ACCESS_TOKEN) return process.env.GOOGLE_OAUTH_ACCESS_TOKEN; const r=await fetch('http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token',{headers:{'Metadata-Flavor':'Google'}}); if(!r.ok) throw new Error(`Unable to obtain Google workload identity token (${r.status})`); const d=await r.json() as any; if(!d.access_token) throw new Error('Google workload identity token was not returned'); return d.access_token; }
async function request<T>(url:string,init:RequestInit={}):Promise<T>{ const r=await fetch(url,{...init,headers:{Authorization:`Bearer ${await token()}`,'Content-Type':'application/json',...(init.headers||{})}}); if(!r.ok){const b=await r.text();throw new Error(`Firestore trusted request failed (${r.status}): ${b.slice(0,500)}`)} return r.status===204?{} as T:await r.json() as T; }
async function begin(){const r=await request<{transaction?:string}>(`${BASE}:beginTransaction`,{method:'POST',body:JSON.stringify({options:{readWrite:{}}})});if(!r.transaction)throw new Error('Firestore transaction was not created');return r.transaction;}
async function readTx(n:string,t:string){try{return fromDoc(await request<Doc>(`${n}?transaction=${encodeURIComponent(t)}`));}catch(e){if(String(e).includes('(404)'))return null;throw e;}}
async function commit(t:string,w:Array<{name:string,data:Record<string,unknown>}>){await request(`${BASE}:commit`,{method:'POST',body:JSON.stringify({transaction:t,writes:w.map(x=>({update:toDoc(x.name,x.data)}))})});}
async function rollback(t:string){try{await request(`${BASE}:rollback`,{method:'POST',body:JSON.stringify({transaction:t})});}catch{}}
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
const RE=/^[A-Za-z0-9._:-]{8,128}$/;

export interface CandidateProjectionRequest { actorUid:string; campaignId:string; studentId:string; requestId:string }
export async function provisionCandidateProjection(input:CandidateProjectionRequest):Promise<{projectionId:string;replayed:boolean}>{
 if(!RE.test(input.requestId))throw new Error('Invalid requestId'); const t=await begin(); try{
  const [actor,campaign,student]=await Promise.all([readTx(nameOf('users',input.actorUid),t),readTx(nameOf('campaigns',input.campaignId),t),readTx(nameOf('students',input.studentId),t)]);
  if(!actor||!campaign||!student)throw new Error('Required recruitment records were not found');
  if(!['employer','institution'].includes(actor.role))throw new Error('Only employers or institutions may provision candidate projections');
  if(actor.role==='employer'&&campaign.employerId!==input.actorUid)throw new Error('Employer is not authorized for this campaign');
  if(actor.role==='institution'&&(!Array.isArray(campaign.targetedInstitutionIds)||!campaign.targetedInstitutionIds.includes(input.actorUid)))throw new Error('Institution is not targeted by this campaign');
  if(actor.role==='institution'&&student.institutionId!==input.actorUid)throw new Error('Institution is not authorized for this student');
  const consent=student.campaignConsents?.[input.campaignId]; if(!consent||consent.status!=='approved')throw new Error('Explicit campaign consent is required before projection'); if(consent.employerId!==campaign.employerId)throw new Error('Consent does not match the campaign employer');
  const id=hash(`${campaign.employerId}:${input.campaignId}:${input.studentId}`), pn=nameOf('candidateProfiles',id), an=nameOf('auditEvents',hash(`${input.requestId}:${input.actorUid}:${input.campaignId}:${input.studentId}`));
  const [existing,existingAudit]=await Promise.all([readTx(pn,t),readTx(an,t)]); if(existingAudit){await rollback(t);return {projectionId:id,replayed:true};}
  const projection:any={studentId:input.studentId,employerId:campaign.employerId,campaignId:input.campaignId,role:campaign.requirement?.role||'Hiring Opportunity',name:student.name||'Candidate',institutionId:student.institutionId||'',institutionName:student.institutionName||'',candidateType:student.candidateType||'unknown',consentStatus:'approved',consentUpdatedAt:consent.updatedAt||new Date().toISOString(),projectionVersion:1,updatedAt:new Date().toISOString()};
  if(consent.academicDataShared)Object.assign(projection,{program:student.program||'',branch:student.branch||'',graduationYear:student.graduationYear||0,cgpa:student.cgpa||0});
  if(consent.skillBenchmarksShared)projection.verifiedSkills=Array.isArray(student.skills)?student.skills.filter((s:any)=>['Gold','Silver','Bronze','Verified'].includes(s?.badge)).map((s:any)=>({name:s.name,category:s.category,score:s.score,badge:s.badge})):[];
  if(consent.projectReposShared)projection.projects=Array.isArray(student.projects)?student.projects:[]; if(consent.contactInfoShared)projection.email=student.email||'';
  const audit={eventId:an.split('/').pop(),requestId:input.requestId,actorUid:input.actorUid,actorRole:actor.role,subjectStudentId:input.studentId,employerId:campaign.employerId,campaignId:input.campaignId,action:'CANDIDATE_PROJECTION_PROVISIONED',consentScope:{academicDataShared:!!consent.academicDataShared,skillBenchmarksShared:!!consent.skillBenchmarksShared,projectReposShared:!!consent.projectReposShared,contactInfoShared:!!consent.contactInfoShared},projectionId:id,timestamp:new Date().toISOString(),immutable:true};
  await commit(t,existing?[{name:an,data:audit}]:[{name:pn,data:projection},{name:an,data:audit}]); return {projectionId:id,replayed:false};
 }catch(e){await rollback(t);throw e;}}

export type RecruitmentTransitionAction='CREATE_REQUIREMENT_CAMPAIGN'|'SEND_CALLS'|'RESPOND_CALL'|'ACTIVATE_STUDENTS'|'SUBMIT_CONSENT'|'UPDATE_CONSENT_SCOPE'|'GLOBAL_CONSENT'|'ADVANCE_CANDIDATE_STAGE';
export interface RecruitmentTransitionRequest { actorUid:string; requestId:string; action:RecruitmentTransitionAction; payload:Record<string,any> }
export interface RecruitmentTransitionResult { replayed:boolean; auditEventId:string; ids:string[] }
const auditId=(i:RecruitmentTransitionRequest)=>hash(`${i.requestId}:${i.actorUid}:${i.action}`);
const role=(a:any,roles:string[])=>{if(!roles.includes(a.role))throw new Error(`Role ${a.role||'unknown'} is not authorized for ${roles.join('/')}`)};
const stages=['invited','assessment_pending','assessment_completed','shortlisted','interviewing','offered','accepted','joined','declined'];
const counted:Record<string,string>={assessment_completed:'assessmentsCompleted',shortlisted:'shortlisted',interviewing:'interviewed',offered:'offersMade',accepted:'offersAccepted',joined:'joined'};

export async function executeRecruitmentTransition(input:RecruitmentTransitionRequest):Promise<RecruitmentTransitionResult>{
 if(!RE.test(input.requestId))throw new Error('Invalid requestId'); const t=await begin(); try{
  const aid=auditId(input),an=nameOf('auditEvents',aid),existing=await readTx(an,t); if(existing){await rollback(t);return {replayed:true,auditEventId:aid,ids:[]};}
  const actor=await readTx(nameOf('users',input.actorUid),t); if(!actor)throw new Error('Actor record was not found'); const p=input.payload||{},now=new Date().toISOString(); const writes:any[]=[],ids:string[]=[];
  const read=async(c:string,id:string)=>readTx(nameOf(c,id),t); const must=async(c:string,id:string)=>{const v=await read(c,id);if(!v)throw new Error(`${c}/${id} was not found`);return v;};
  switch(input.action){
   case 'CREATE_REQUIREMENT_CAMPAIGN':{role(actor,['employer']);const r=clone(p.requirement),c=clone(p.campaign);if(!r?.id||!c?.id||c.requirementId!==r.id)throw new Error('Requirement and campaign identifiers are required and must match');if(r.employerId!==input.actorUid||c.employerId!==input.actorUid)throw new Error('Employer ownership mismatch');if(await read('requirements',r.id)||await read('campaigns',c.id))throw new Error('Recruitment identifiers already exist; refusing to overwrite');writes.push({name:nameOf('requirements',r.id),data:r},{name:nameOf('campaigns',c.id),data:c});ids.push(r.id,c.id);break;}
   case 'SEND_CALLS':{role(actor,['employer']);const c=await must('campaigns',p.campaignId);if(c.employerId!==input.actorUid)throw new Error('Employer is not authorized for this campaign');const calls=Array.isArray(p.calls)?p.calls:[];if(!calls.length)throw new Error('At least one call is required');const seen=new Set<string>();for(const call of calls){if(!call.id||call.campaignId!==c.id||call.employerId!==input.actorUid)throw new Error('Call ownership or campaign mismatch');if(seen.has(call.id)||await read('calls',call.id))throw new Error('One or more call identifiers already exist');seen.add(call.id);writes.push({name:nameOf('calls',call.id),data:call});}const targeted=Array.from(new Set([...(Array.isArray(c.targetedInstitutionIds)?c.targetedInstitutionIds:[]),...calls.map((x:any)=>x.institutionId)]));writes.push({name:nameOf('campaigns',c.id),data:{...c,targetedInstitutionIds:targeted,callsSent:[...(Array.isArray(c.callsSent)?c.callsSent:[]),...calls],funnel:{...c.funnel,institutionsInvited:targeted.length}}});ids.push(...calls.map((x:any)=>x.id),c.id);break;}
   case 'RESPOND_CALL':{role(actor,['institution']);const call=await must('calls',p.callId);if(call.institutionId!==input.actorUid)throw new Error('Institution is not authorized for this call');const c=await must('campaigns',call.campaignId);if(call.status!=='pending')throw new Error('Call has already been responded to');if(!['accepted','declined','countered'].includes(p.status))throw new Error('Invalid call status');const updated={...call,status:p.status,responseNotes:String(p.responseNotes||''),offeredCandidatesCount:p.offeredCandidatesCount??call.vacanciesRequested*2,counterDaysExtension:p.counterDaysExtension,respondedAt:now};const f={...c.funnel,institutionsAccepted:Number(c.funnel?.institutionsAccepted||0)+(p.status==='declined'?0:1)};writes.push({name:nameOf('calls',call.id),data:updated},{name:nameOf('campaigns',c.id),data:{...c,funnel:f}});ids.push(call.id,c.id);break;}
   case 'ACTIVATE_STUDENTS':{role(actor,['institution']);const call=await must('calls',p.callId);if(call.institutionId!==input.actorUid)throw new Error('Institution is not authorized for this call');const c=await must('campaigns',call.campaignId);const studentIds=Array.isArray(p.studentIds)?Array.from(new Set(p.studentIds)):[];if(!studentIds.length)throw new Error('At least one student is required');const opps:any[]=[];for(const sid of studentIds){const s=await must('students',sid);if(s.institutionId!==input.actorUid)throw new Error('Institution is not authorized for one or more students');const id=String(p.opportunityIds?.[sid]||hash(`${call.id}:${sid}`));if(await read('opportunities',id))throw new Error('Opportunity already exists; refusing to duplicate');opps.push({id,callId:call.id,campaignId:c.id,employerId:call.employerId,employerName:call.employerName,role:call.role,salaryLPA:c.requirement?.salaryMinLPA||0,locations:call.locations,joiningWindow:call.joiningWindow,studentId:sid,studentName:s.name||'Student',institutionId:call.institutionId,institutionName:call.institutionName,matchScore:0,matchBreakdown:{skillMatchScore:0,academicMatchScore:0,preferenceMatchScore:0,aiRationale:'Candidate activated through institutional workflow; human evaluation required.'},stage:'invited',invitedAt:now,stageUpdatedAt:now});}for(const o of opps)writes.push({name:nameOf('opportunities',o.id),data:o});writes.push({name:nameOf('campaigns',c.id),data:{...c,candidateOpportunities:[...(Array.isArray(c.candidateOpportunities)?c.candidateOpportunities:[]),...opps],funnel:{...c.funnel,studentsInvited:Number(c.funnel?.studentsInvited||0)+opps.length}}});ids.push(...opps.map(o=>o.id),c.id);break;}
   case 'SUBMIT_CONSENT':{role(actor,['student']);const o=await must('opportunities',p.opportunityId);if(o.studentId!==input.actorUid)throw new Error('Student is not authorized for this opportunity');const c=await must('campaigns',o.campaignId);const yes=Boolean(p.consented),next=yes?'assessment_pending':'declined';if(!['invited','declined','assessment_pending'].includes(o.stage))throw new Error('Opportunity is not in a consentable state');const f={...c.funnel};if(yes&&o.stage!=='assessment_pending')f.applicationsConsented=Number(f.applicationsConsented||0)+1;if(!yes&&o.stage==='assessment_pending')f.applicationsConsented=Math.max(0,Number(f.applicationsConsented||0)-1);writes.push({name:nameOf('opportunities',o.id),data:{...o,stage:next,consentedAt:yes?now:undefined,stageUpdatedAt:now}},{name:nameOf('campaigns',c.id),data:{...c,funnel:f}});ids.push(o.id,c.id);break;}
   case 'UPDATE_CONSENT_SCOPE':{role(actor,['student']);const s=await must('students',input.actorUid),cid=String(p.campaignId),cons={...(s.campaignConsents||{})},cur=cons[cid];if(!cur||cur.status!=='approved')throw new Error('Approved campaign consent is required before changing scope');if(!['academicDataShared','skillBenchmarksShared','projectReposShared','contactInfoShared'].includes(p.scopeKey))throw new Error('Invalid consent scope');cons[cid]={...cur,[p.scopeKey]:Boolean(p.value),updatedAt:now};writes.push({name:nameOf('students',input.actorUid),data:{...s,campaignConsents:cons}});ids.push(input.actorUid,cid);break;}
   case 'GLOBAL_CONSENT':{role(actor,['student']);const s=await must('students',input.actorUid);const idsRequested=Array.isArray(p.campaignIds)?p.campaignIds:Array.isArray(p.campaigns)?p.campaigns.map((c:any)=>c?.id):[];const unique=Array.from(new Set(idsRequested.filter((x:any)=>typeof x==='string'&&x.length>0))) as string[];if(!unique.length)throw new Error('At least one campaign is required');const cons={...(s.campaignConsents||{})};for(const cid of unique){const c=await must('campaigns',cid);const eligible=Array.isArray(c.targetedInstitutionIds)&&s.institutionId&&c.targetedInstitutionIds.includes(s.institutionId);if(!eligible)throw new Error('Student is not eligible for one or more requested campaigns');cons[cid]={campaignId:cid,employerId:c.employerId,employerName:c.employerName,role:c.requirement?.role||'Hiring Opportunity',salaryLPA:`₹${c.requirement?.salaryMinLPA||0} - ${c.requirement?.salaryMaxLPA||0} LPA`,status:p.approved?'approved':'denied',academicDataShared:Boolean(p.approved),skillBenchmarksShared:Boolean(p.approved),projectReposShared:Boolean(p.approved),contactInfoShared:Boolean(p.approved),updatedAt:now,...(p.approved?{}:{reasonForDenial:'Student engaged Global Privacy Lock.'})};}writes.push({name:nameOf('students',input.actorUid),data:{...s,campaignConsents:cons}});ids.push(input.actorUid,...unique);break;}
   case 'ADVANCE_CANDIDATE_STAGE':{const o=await must('opportunities',p.opportunityId);role(actor,['employer','institution','student']);if(actor.role==='employer'&&o.employerId!==input.actorUid)throw new Error('Employer is not authorized for this opportunity');if(actor.role==='institution'&&o.institutionId!==input.actorUid)throw new Error('Institution is not authorized for this opportunity');if(actor.role==='student'&&o.studentId!==input.actorUid)throw new Error('Student is not authorized for this opportunity');const next=p.nextStage;if(!stages.includes(next))throw new Error('Invalid recruitment stage');const c=await must('campaigns',o.campaignId),f={...c.funnel};const old=o.stage;if(counted[next]&&old!==next){const marker=`funnelCountedStages.${next}`;const markers={...(o.funnelCountedStages||{})};if(!markers[next]){f[counted[next]]=Number(f[counted[next]]||0)+1;markers[next]=true;} }const updated={...o,stage:next,assessmentScore:p.meta?.assessmentScore??o.assessmentScore,interviewFeedback:p.meta?.interviewFeedback??o.interviewFeedback,offerLetterUrl:p.meta?.offerLetterUrl??o.offerLetterUrl,stageUpdatedAt:now,funnelCountedStages:{...(o.funnelCountedStages||{}),...(old!==next&&counted[next]?{[next]:true}:{})}};writes.push({name:nameOf('opportunities',o.id),data:updated},{name:nameOf('campaigns',c.id),data:{...c,funnel:f}});if(next==='joined'||next==='accepted'){const s=await must('students',o.studentId);writes.push({name:nameOf('students',o.studentId),data:{...s,placementStatus:'placed',placedCompany:o.employerName,placedSalaryLPA:o.salaryLPA,availability:'not_currently_available'}});}ids.push(o.id,c.id);break;}
   default:throw new Error('Unsupported recruitment transition');
  }
  writes.push({name:an,data:{eventId:aid,requestId:input.requestId,actorUid:input.actorUid,actorRole:actor.role,action:input.action,ids,timestamp:now,immutable:true}});await commit(t,writes);return {replayed:false,auditEventId:aid,ids};
 }catch(e){await rollback(t);throw e;}}
